const projects = {
  project1: {
    title: "30 projects",
    subtitle: "A big project involving multiple concepts and technologies.",
    icon: "30projectsIcon.png",
    highlights: ["API's", "Custom Canvas", "JavaScript modules"],
    imgs: [
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
      "30projects1.png",
    ],
    text: "A project made to test and showcase different skills. Things like a custom canvas at the homepage to create a matrix effect, consumption of different api's, css, scss, some bootstrap and many different applications of JavaScript.",
    link: "https://davidbitner.github.io/30-projects/",
  },
  project2: {
    title: "Landings Page",
    subtitle: "A landing page.",
    icon: "landingsPageIcon.png",
    highlights: [
      "Landing Page",
      "Splide Carousel",
      "Ken Burns Effect",
      "Modal",
    ],
    imgs: [
      "landingsPage1.png",
      "landingsPage2.png",
      "landingsPage3.png",
      "landingsPage4.png",
      "landingsPage5.png",
      "landingsPage6.png",
    ],
    text: "A landing page made using certain concepts of agile software development like sprints, a mental map, class diagram and others. Complex bezier animations to create a cool cinematrographic effect on the main banner, multiple transition animations, modals, all using BEM naming pattern.",
    link: "https://davidbitner.github.io/landings-page/",
  },
  project3: {
    title: "Auto Blog",
    subtitle: "A blog that generates random posts.",
    icon: "autoBlogIcon.png",
    highlights: ["Blog", "API", "Loading info"],
    imgs: ["autoBlog1.png", "autoBlog2.png", "autoBlog3.png"],
    text: "This is a website that uses the newscather api to generate news based on a topic, with the information from the api a blog post is automatically generated. The website is 100% responsive and buttons have a ripple effect animation created in CSS and JS. Posts also have a loading state while the api is working in the background, just to make sure the user don't get confused and thinks nothing is happening.",
    link: "https://davidbitner.github.io/auto-blog/",
  },
  project4: {
    title: "Crud",
    subtitle: "A crud website created using JavaScript classes.",
    icon: "crudIcon.png",
    highlights: ["JS Classes", "CRUD"],
    imgs: ["crud1.png", "crud2.png", "crud3.png"],
    text: "An application with cards, these cards can be visualized, can be created, updated and deleted. Information inside the cards can also be manipulated. Application have a grid based layout and is 100% responsive. A modal is oppened every time a card demands to be created, changed or deleted. Local storage is used so no information is lost when the application is closed.",
    link: "https://github.com/DavidBitner/crud/",
  },
  project5: {
    title: "Shapes Colors",
    subtitle:
      "A website created specifically to learn how container manipulation, mouse position and keyboard keys events work.",
    icon: "shapesColorsIcon.png",
    highlights: ["Mouse Position", "Keyboard Options"],
    imgs: [
      "shapesColors1.png",
      "shapesColors2.png",
      "shapesColors3.png",
      "shapesColors4.png",
      "shapesColors5.png",
    ],
    text: "Website with some cool container manipulation based on mouse position and a set of options. Options can be changed via key presses that are handled in JavaScript. Options like change background color, change shape of container, color of container and make the container bigger or smaller.",
    link: "https://davidbitner.github.io/shapes-colors/",
  },
  project6: {
    title: "Timers",
    subtitle: "An application with multiple timers.",
    icon: "timersIcon.png",
    highlights: ["Set Interval", "Modal", "Grid Responsivenes"],
    imgs: ["timers1.png", "timers2.png", "timers3.png"],
    text: "Multiple timers in a responsive grid. Timers can be added, removed, reset and changed based on the options available inside a modal. Timers also have a progress bar based on how much time is left until the timer ends. Also a sound is played every time a timer ends.",
    link: "https://davidbitner.github.io/timers/",
  },
};

export { projects };
