export const data = {
  about: {
    en: [
      "Web Developer focused on creating scalable solutions and performant interfaces. Specialist in transforming complex requirements into clean, maintainable code.",
      "As a professional, I maintain a high level of dedication, taking full responsibility for my work. I employ an analytical approach to troubleshooting, focusing on performance optimization and UX.",
      "In addition to my passion for technology, I am an enthusiast of nerd culture. This interest enriches my creativity and has been instrumental in connecting with people worldwide.",
      "I am always open to opportunities. Feel free to contact me via email at <a href='mailto:david-bitner@hotmail.com'>david-bitner@hotmail.com</a>.",
    ],
    pt: [
      "Desenvolvedor Web focado em criar soluções escaláveis e interfaces performáticas. Especialista em transformar requisitos complexos em código limpo e manutenível.",
      "Como profissional, mantenho um alto nível de dedicação, assumindo total responsabilidade pelo meu trabalho. Utilizo uma abordagem analítica para resolução de problemas, focando em otimização de performance e UX.",
      "Além da minha paixão por tecnologia, sou um entusiasta da cultura nerd. Esse interesse enriquece minha criatividade e tem sido fundamental para criar conexões com pessoas ao redor do mundo.",
      "Estou sempre aberto a oportunidades. Sinta-se à vontade para entrar em contato comigo através do email <a href='mailto:david-bitner@hotmail.com'>david-bitner@hotmail.com</a>.",
    ],
  },

  projects: [
    // --- PROJETOS DESTAQUE (Grid Principal) ---
    {
      id: "project1",
      highlight: true,
      title: "30 Projects",
      imgCover: "project1.png",
      icon: "30projectsIcon.png",
      link: "https://davidbitner.github.io/30-projects/",
      imgs: Array.from({ length: 13 }, (_, i) => `30projects${i + 1}.png`),
      color: "#195020",
      en: {
        title: "30 Projects",
        subtitle: "A massive project involving multiple concepts.",
        highlights: ["API's", "Custom Canvas", "JS Modules"],
        text: "A comprehensive showcase of skills. Features a custom canvas matrix effect, consumption of multiple APIs, advanced CSS/SCSS, Bootstrap integration, and diverse JavaScript applications.",
      },
      pt: {
        title: "30 Projetos",
        subtitle: "Um projeto massivo envolvendo múltiplos conceitos.",
        highlights: ["API's", "Custom Canvas", "JS Modules"],
        text: "Uma demonstração abrangente de habilidades. Apresenta efeito matrix em canvas, consumo de múltiplas APIs, CSS/SCSS avançado, integração com Bootstrap e diversas aplicações JavaScript.",
      },
    },
    {
      id: "project2",
      highlight: true,
      title: "Landings Page",
      imgCover: "project2.png",
      icon: "landingsPageIcon.png",
      link: "https://davidbitner.github.io/landings-page/",
      imgs: Array.from({ length: 6 }, (_, i) => `landingsPage${i + 1}.png`),
      color: "#714f3b",
      en: {
        title: "Landings Page",
        subtitle: "High-conversion landing page structure.",
        highlights: ["Agile", "Splide Carousel", "Ken Burns Effect"],
        text: "Developed using Agile concepts (Sprints, Mind Maps). Features complex bezier animations creating a cinematic Ken Burns effect on the main banner.",
      },
      pt: {
        title: "Landings Page",
        subtitle: "Estrutura de landing page de alta conversão.",
        highlights: ["Agile", "Splide Carousel", "Ken Burns Effect"],
        text: "Desenvolvido usando conceitos Agile (Sprints, Mapas Mentais). Apresenta animações bezier complexas criando um efeito cinematográfico Ken Burns no banner principal.",
      },
    },
    {
      id: "project3",
      highlight: true,
      title: "Auto Blog",
      imgCover: "project3.png",
      icon: "autoBlogIcon.png",
      link: "https://davidbitner.github.io/auto-blog/",
      imgs: ["autoBlog1.png", "autoBlog2.png", "autoBlog3.png"],
      color: "#886a84",
      en: {
        title: "Auto Blog",
        subtitle: "Automated content generation platform.",
        highlights: ["Newscatcher API", "Async/Await", "DOM Manipulation"],
        text: "Uses the Newscatcher API to fetch real-time news based on topics and automatically generates formatted blog posts.",
      },
      pt: {
        title: "Auto Blog",
        subtitle: "Plataforma de geração automática de conteúdo.",
        highlights: ["Newscatcher API", "Async/Await", "DOM Manipulation"],
        text: "Utiliza a API Newscatcher para buscar notícias em tempo real baseadas em tópicos e gera automaticamente posts de blog formatados.",
      },
    },
    {
      id: "project4",
      highlight: true,
      title: "CRUD",
      imgCover: "project4.png",
      icon: "crudIcon.png",
      link: "https://davidbitner.github.io/crud/",
      imgs: ["crud1.png", "crud2.png", "crud3.png"],
      color: "#606060",
      en: {
        title: "CRUD Application",
        subtitle: "Data management system with persistence.",
        highlights: ["JS Classes", "LocalStorage", "State Management"],
        text: "Full Create-Read-Update-Delete application. Features modal interfaces for data entry and LocalStorage implementation for data persistence.",
      },
      pt: {
        title: "Aplicação CRUD",
        subtitle: "Sistema de gerenciamento de dados com persistência.",
        highlights: ["Classes JS", "LocalStorage", "Gestão de Estado"],
        text: "Aplicação completa de Create-Read-Update-Delete. Possui interfaces modais para entrada de dados e implementação de LocalStorage para persistência.",
      },
    },
    {
      id: "project5",
      highlight: true,
      title: "Shapes and colors",
      imgCover: "project5.png",
      icon: "shapesColorsIcon.png",
      link: "https://davidbitner.github.io/shapes-colors/",
      imgs: Array.from({ length: 5 }, (_, i) => `shapesColors${i + 1}.png`),
      color: "#000533",
      en: {
        title: "Shapes & Colors",
        subtitle: "Interactive DOM manipulation study.",
        highlights: ["Event Listeners", "Keyboard Events", "CSS Variables"],
        text: "Interactive sandbox exploring container manipulation via mouse coordinates and keyboard events to alter shapes, colors, and dimensions dynamically.",
      },
      pt: {
        title: "Shapes & Colors",
        subtitle: "Estudo interativo de manipulação do DOM.",
        highlights: ["Event Listeners", "Eventos de Teclado", "Variáveis CSS"],
        text: "Sandbox interativo explorando manipulação de containers via coordenadas do mouse e eventos de teclado para alterar formas, cores e dimensões dinamicamente.",
      },
    },
    {
      id: "project6",
      highlight: true,
      title: "Movie Guide",
      imgCover: "project6.png",
      icon: "movieGuideIcon.png",
      link: "https://davidbitner.github.io/movie-guide/",
      imgs: ["movieGuide1.png", "movieGuide2.png", "movieGuide3.png"],
      color: "#771111",
      en: {
        title: "Movie Guide",
        subtitle: "Cinema database interface.",
        highlights: ["REST API", "Responsive Grid", "Error Handling"],
        text: "Movie search engine integrating with external APIs to display detailed metadata, ratings, and posters with a fully responsive layout.",
      },
      pt: {
        title: "Guia de Filmes",
        subtitle: "Interface de banco de dados de cinema.",
        highlights: ["REST API", "Grid Responsivo", "Tratamento de Erros"],
        text: "Mecanismo de busca de filmes integrando com APIs externas para exibir metadados detalhados, avaliações e pôsteres com layout totalmente responsivo.",
      },
    },

    // --- OUTROS PROJETOS (Modal) ---
    {
      id: "other-bcc",
      highlight: false,
      title: "Blue Crystal Calculator",
      link: "https://davidbitner.github.io/blue-crystal-calculator/",
      imgCover: "projects/bcc.png",
    },
    {
      id: "other-dictionary",
      highlight: false,
      title: "Dictionary",
      link: "https://davidbitner.github.io/dictionary/",
      imgCover: "projects/dictionary.png",
    },
    {
      id: "other-odp",
      highlight: false,
      title: "ODP",
      link: "https://davidbitner.github.io/odp/",
      imgCover: "projects/odp.png",
    },
    {
      id: "other-timers",
      highlight: false,
      title: "Timers",
      link: "https://davidbitner.github.io/timers/",
      imgCover: "projects/timers.png",
    },
    {
      id: "other-login",
      highlight: false,
      title: "Login",
      link: "https://davidbitner.github.io/login/",
      imgCover: "projects/login.png",
    },
    {
      id: "other-quiz",
      highlight: false,
      title: "Quiz APP",
      link: "https://davidbitner.github.io/quiz-app/",
      imgCover: "projects/quizApp.png",
    },
    {
      id: "other-slider",
      highlight: false,
      title: "Sliders",
      link: "https://davidbitner.github.io/slider-design/",
      imgCover: "projects/sliders.png",
    },
    {
      id: "other-list",
      highlight: false,
      title: "List",
      link: "https://davidbitner.github.io/list/",
      imgCover: "projects/list.png",
    },
    {
      id: "other-despertador",
      highlight: false,
      title: "Alarm Clock",
      link: "https://davidbitner.github.io/despertador/",
      imgCover: "projects/despertador.png",
    },
  ],

  education: [
    {
      where: "Transwolff",
      period: "2024 - Current",
      en: {
        title: "Operational Control Center",
        text: "Responsible for real-time fleet management, camera monitoring, and comprehensive reporting across diverse operational areas and guidelines. Spearheaded the department's digital transformation by identifying bottlenecks in manual processes and implementing automated spreadsheet solutions, significantly increasing data reliability and operational efficiency.",
      },
      pt: {
        title: "Centro de Controle Operacional",
        text: "Responsável pela gestão de frota em tempo real, monitoramento de câmeras e elaboração de relatórios abrangentes de diversas áreas e diretrizes operacionais. Liderei a transformação digital do setor identificando gargalos em processos manuais e implementando automações em planilhas, aumentando significativamente a confiabilidade dos dados e a eficiência operacional.",
      },
    },
    {
      where: "Freelancer",
      period: "2022 - 2024",
      en: {
        title: "Full Stack Web Developer",
        text: "Developed custom web solutions for diverse clients using HTML, CSS, JavaScript, and React. Managed full project lifecycles, from requirement gathering to deployment and maintenance.",
      },
      pt: {
        title: "Desenvolvedor Web Full Stack",
        text: "Desenvolvi soluções web personalizadas para diversos clientes usando HTML, CSS, JavaScript e React. Gerenciei ciclos completos de projeto, do levantamento de requisitos ao deploy e manutenção.",
      },
    },
    {
      where: "Udemy",
      period: "2021",
      en: {
        title: "The Complete JavaScript Course",
        text: "Intensive mastering of modern JavaScript: ES6+, OOP, AJAX, and Asynchronous JS patterns.",
      },
      pt: {
        title: "Curso Completo de JavaScript",
        text: "Domínio intensivo de JavaScript moderno: ES6+, OOP, AJAX e padrões de JS Assíncrono.",
      },
    },
    {
      where: "Universidade Nove de Julho",
      period: "2016 - 2020",
      en: {
        title: "Bachelor's Degree, Information Systems",
        text: "Academic focus on Software Engineering, Database Management, System Analysis, and Project Management methodologies.",
      },
      pt: {
        title: "Bacharelado em Sistemas da Informação",
        text: "Foco acadêmico em Engenharia de Software, Gestão de Banco de Dados, Análise de Sistemas e metodologias de Gestão de Projetos.",
      },
    },
    {
      where: "Curso em Video",
      period: "2020",
      en: {
        title: "Git and GitHub",
        text: "Version control fundamentals, branching strategies, and collaborative workflows.",
      },
      pt: {
        title: "Git e GitHub",
        text: "Fundamentos de controle de versão, estratégias de branching e fluxos de trabalho colaborativos.",
      },
    },
  ],
  skills: {
    tech: ["JavaScript (ES6+)", "Sass / SCSS", "CSS3", "HTML5", "Python"],
    tools: [
      "VS Code",
      "Git & GitHub",
      "Adobe XD",
      "Photoshop",
      "Trello",
      "Excel",
    ],
    soft: {
      en: [
        "Agile Methodologies",
        "Troubleshooting",
        "Adaptability",
        "Technical Documentation",
        "Professional Ethics",
      ],
      pt: [
        "Metodologias Ágeis",
        "Resolução de Problemas",
        "Adaptabilidade",
        "Documentação Técnica",
        "Ética Profissional",
      ],
    },
    languages: {
      en: ["Portuguese - Native", "English - Fluent", "Spanish - Basic"],
      pt: ["Português - Nativo", "Inglês - Fluente", "Espanhol - Básico"],
    },
  },
};
